import { Recipient } from './recipient.model';

export const MOCKRECIPIENTS: Recipient[] = [
    {
        id: '1',
        name: 'Greg',
        address: '16432 57th Ave SE',
        email: 'gregfcarlson@gmail.com',
        imageUrl: '../../assets/images/greg.jpg'
    },
    {
        id: '2',
        name: 'Chris',
        address: '16432 57th Ave SE',
        email: 'chrisacarlson@comcast.net',
        imageUrl: '../../assets/images/chris.jpg'
    },
    {
        id: '3',
        name: 'Stephanie',
        address: '16432 57th Ave SE',
        email: 'stephanieacarlson.sunshine@gmail.com',
        imageUrl: '../../assets/images/stephanie.jpg'
    },
    {
        id: '4',
        name: 'Michael',
        address: '2098 Cousteau Dr',
        email: 'michael.carlson314@gmail.com',
        imageUrl: '../../assets/images/michael.jpg'
    },
    {
        id: '5',
        name: 'Lily',
        address: '2098 Cousteau Dr',
        email: 'l.hamelaswood@gmail.com',
        imageUrl: '../../assets/images/lily.jpg'
    },
    {
        id: '6',
        name: 'Rowan',
        address: '2098 Cousteau Dr',
        email: '',
        imageUrl: '../../assets/images/rowan.jpg'
    },
    {
        id: '7',
        name: 'Spencer',
        address: '16432 57th Ave SE',
        email: 'spencerthecarlson@gmail.com',
        imageUrl: '../../assets/images/spencer.jpg'
    },
    {
        id: '8',
        name: 'Evan',
        address: '1207 Westglen Dr',
        email: 'res0uyha@gmail.com',
        imageUrl: '../../assets/images/evan.jpg'
    },
    {
        id: '9',
        name: 'Michelle',
        address: '1207 Westglen Dr',
        email: 'fake2@email.com',
        imageUrl: '../../assets/images/michelle.jpg'
    },
    {
        id: '10',
        name: 'David',
        address: '1207 Westglen Dr',
        email: 'wompy531@gmail.com ',
        imageUrl: '../../assets/images/david.jpg'
    },
    {
        id: '11',
        name: 'Sam',
        address: '1207 Westglen Dr',
        email: 'howarth179@gmail.com',
        imageUrl: '../../assets/images/sam.jpg'
    },
    {
        id: '12',
        name: 'Nathan',
        address: '1207 Westglen Dr',
        email: 'fake2@email.com',
        imageUrl: '../../assets/images/nathan.jpg'
    }
];